$rosewaterAlpha = f2d5cf
$flamingoAlpha  = eebebe
$pinkAlpha      = f4b8e4
$mauveAlpha     = ca9ee6
$redAlpha       = e78284
$maroonAlpha    = ea999c
$peachAlpha     = ef9f76
$yellowAlpha    = e5c890
$greenAlpha     = a6d189
$tealAlpha      = 81c8be
$skyAlpha       = 99d1db
$sapphireAlpha  = 85c1dc
$blueAlpha      = 8caaee
$lavenderAlpha  = babbf1

$textAlpha      = c6d0f5
$subtext1Alpha  = b5bfe2
$subtext0Alpha  = a5adce

$overlay2Alpha  = 949cbb
$overlay1Alpha  = 838ba7
$overlay0Alpha  = 737994

$surface2Alpha  = 626880
$surface1Alpha  = 51576d
$surface0Alpha  = 414559

$baseAlpha      = 303446
$mantleAlpha    = 292c3c
$crustAlpha     = 232634

$rosewater = rgb(242, 214, 208)
$flamingo  = rgb(238, 190, 190)
$pink      = rgb(244, 184, 228)
$mauve     = rgb(202, 158, 230)
$red       = rgb(231, 131, 132)
$maroon    = rgb(234, 154, 156)
$peach     = rgb(239, 159, 119)
$yellow    = rgb(229, 201, 145)
$green     = rgb(166, 209, 137)
$teal      = rgb(130, 200, 191)
$sky       = rgb(130, 200, 191)
$sapphire  = rgb(134, 193, 220)
$blue      = rgb(140, 169, 238)
$lavender  = rgb(187, 188, 241)

$text      = rgb(199, 209, 245)
$subtext1  = rgb(182, 191, 226)
$subtext0  = rgb(166, 174, 206)

$overlay2  = rgb(149, 156, 187)
$overlay1  = rgb(131, 139, 167)
$overlay0  = rgb(116, 122, 148)

$surface2  = rgb(98, 104, 128)
$surface1  = rgb(81, 87, 109)
$surface0  = rgb(65, 69, 89)

$base      = rgb(48, 52, 70)
$mantle    = rgb(41, 44, 61)
$crust     = rgb(35, 39, 53)
