$rosewaterAlpha = f4dbd6
$flamingoAlpha  = f0c6c6
$pinkAlpha      = f5bde6
$mauveAlpha     = c6a0f6
$redAlpha       = ed8796
$maroonAlpha    = ee99a0
$peachAlpha     = f5a97f
$yellowAlpha    = eed49f
$greenAlpha     = a6da95
$tealAlpha      = 8bd5ca
$skyAlpha       = 91d7e3
$sapphireAlpha  = 7dc4e4
$blueAlpha      = 8aadf4
$lavenderAlpha  = b7bdf8

$textAlpha      = cad3f5
$subtext1Alpha  = b8c0e0
$subtext0Alpha  = a5adcb

$overlay2Alpha  = 939ab7
$overlay1Alpha  = 8087a2
$overlay0Alpha  = 6e738d

$surface2Alpha  = 5b6078
$surface1Alpha  = 494d64
$surface0Alpha  = 363a4f

$baseAlpha      = 24273a
$mantleAlpha    = 1e2030
$crustAlpha     = 181926

$rosewater = rgb(244, 219, 214)
$flamingo  = rgb(240, 198, 198)
$pink      = rgb(245, 189, 230)
$mauve     = rgb(199, 160, 246)
$red       = rgb(237, 135, 150)
$maroon    = rgb(238, 154, 161)
$peach     = rgb(245, 168, 127)
$yellow    = rgb(238, 212, 160)
$green     = rgb(167, 218, 150)
$teal      = rgb(139, 213, 202)
$sky       = rgb(139, 213, 202)
$sapphire  = rgb(126, 196, 228)
$blue      = rgb(138, 173, 244)
$lavender  = rgb(184, 190, 248)

$text      = rgb(203, 212, 245)
$subtext1  = rgb(184, 192, 224)
$subtext0  = rgb(165, 173, 203)

$overlay2  = rgb(147, 154, 183)
$overlay1  = rgb(128, 135, 162)
$overlay0  = rgb(111, 116, 141)

$surface2  = rgb(91, 96, 121)
$surface1  = rgb(73, 77, 101)
$surface0  = rgb(54, 59, 80)

$base      = rgb(36, 39, 58)
$mantle    = rgb(30, 32, 48)
$crust     = rgb(24, 25, 38)
