$rosewaterAlpha = f5e0dc
$flamingoAlpha  = f2cdcd
$pinkAlpha      = f5c2e7
$mauveAlpha     = cba6f7
$redAlpha       = f38ba8
$maroonAlpha    = eba0ac
$peachAlpha     = fab387
$yellowAlpha    = f9e2af
$greenAlpha     = a6e3a1
$tealAlpha      = 94e2d5
$skyAlpha       = 89dceb
$sapphireAlpha  = 74c7ec
$blueAlpha      = 89b4fa
$lavenderAlpha  = b4befe

$textAlpha      = cdd6f4
$subtext1Alpha  = bac2de
$subtext0Alpha  = a6adc8

$overlay2Alpha  = 9399b2
$overlay1Alpha  = 7f849c
$overlay0Alpha  = 6c7086

$surface2Alpha  = 585b70
$surface1Alpha  = 45475a
$surface0Alpha  = 313244

$baseAlpha      = 1e1e2e
$mantleAlpha    = 181825
$crustAlpha     = 11111b

$rosewater = rgb(245, 225, 221)
$flamingo  = rgb(242, 206, 206)
$pink      = rgb(245, 195, 232)
$mauve     = rgb(203, 167, 247)
$red       = rgb(243, 139, 168)
$maroon    = rgb(235, 161, 173)
$peach     = rgb(250, 180, 136)
$yellow    = rgb(249, 226, 175)
$green     = rgb(166, 227, 161)
$teal      = rgb(148, 226, 213)
$sky       = rgb(148, 226, 213)
$sapphire  = rgb(116, 198, 236)
$blue      = rgb(138, 181, 250)
$lavender  = rgb(180, 190, 254)

$text      = rgb(206, 215, 244)
$subtext1  = rgb(186, 194, 222)
$subtext0  = rgb(166, 173, 200)

$overlay2  = rgb(147, 154, 179)
$overlay1  = rgb(127, 132, 157)
$overlay0  = rgb(108, 112, 134)

$surface2  = rgb(88, 91, 112)
$surface1  = rgb(69, 71, 91)
$surface0  = rgb(50, 50, 68)

$base      = rgb(30, 30, 46)
$mantle    = rgb(24, 24, 38)
$crust     = rgb(17, 17, 27)
