$rosewaterAlpha = dc8a78
$flamingoAlpha  = dd7878
$pinkAlpha      = ea76cb
$mauveAlpha     = 8839ef
$redAlpha       = d20f39
$maroonAlpha    = e64553
$peachAlpha     = fe640b
$yellowAlpha    = df8e1d
$greenAlpha     = 40a02b
$tealAlpha      = 179299
$skyAlpha       = 04a5e5
$sapphireAlpha  = 209fb5
$blueAlpha      = 1e66f5
$lavenderAlpha  = 7287fd

$textAlpha      = 4c4f69
$subtext1Alpha  = 5c5f77
$subtext0Alpha  = 6c6f85

$overlay2Alpha  = 7c7f93
$overlay1Alpha  = 8c8fa1
$overlay0Alpha  = 9ca0b0

$surface2Alpha  = acb0be
$surface1Alpha  = bcc0cc
$surface0Alpha  = ccd0da

$baseAlpha      = eff1f5
$mantleAlpha    = e6e9ef
$crustAlpha     = dce0e8

$rosewater = rgb(220, 138, 120)
$flamingo  = rgb(221, 121, 121)
$pink      = rgb(234, 118, 203)
$mauve     = rgb(136, 57, 239)
$red       = rgb(211, 15, 58)
$maroon    = rgb(230, 70, 83)
$peach     = rgb(254, 101, 12)
$yellow    = rgb(223, 142, 29)
$green     = rgb(65, 161, 43)
$teal      = rgb(23, 146, 153)
$sky       = rgb(23, 146, 153)
$sapphire  = rgb(32, 159, 182)
$blue      = rgb(31, 102, 245)
$lavender  = rgb(115, 136, 253)

$text      = rgb(76, 79, 106)
$subtext1  = rgb(92, 95, 120)
$subtext0  = rgb(109, 112, 133)

$overlay2  = rgb(124, 127, 148)
$overlay1  = rgb(140, 144, 162)
$overlay0  = rgb(156, 160, 176)

$surface2  = rgb(172, 176, 190)
$surface1  = rgb(188, 192, 204)
$surface0  = rgb(204, 208, 218)

$base      = rgb(239, 241, 245)
$mantle    = rgb(231, 234, 239)
$crust     = rgb(220, 224, 232)
