$rosewaterAlpha = {{rosewater}}
$flamingoAlpha  = {{flamingo}}
$pinkAlpha      = {{pink}}
$mauveAlpha     = {{mauve}}
$redAlpha       = {{red}}
$maroonAlpha    = {{maroon}}
$peachAlpha     = {{peach}}
$yellowAlpha    = {{yellow}}
$greenAlpha     = {{green}}
$tealAlpha      = {{teal}}
$skyAlpha       = {{sky}}
$sapphireAlpha  = {{sapphire}}
$blueAlpha      = {{blue}}
$lavenderAlpha  = {{lavender}}

$textAlpha      = {{text}}
$subtext1Alpha  = {{subtext1}}
$subtext0Alpha  = {{subtext0}}

$overlay2Alpha  = {{overlay2}}
$overlay1Alpha  = {{overlay1}}
$overlay0Alpha  = {{overlay0}}

$surface2Alpha  = {{surface2}}
$surface1Alpha  = {{surface1}}
$surface0Alpha  = {{surface0}}

$baseAlpha      = {{base}}
$mantleAlpha    = {{mantle}}
$crustAlpha     = {{crust}}

$rosewater = {{ rgb rosewater }}
$flamingo  = {{ rgb flamingo }}
$pink      = {{ rgb pink }}
$mauve     = {{ rgb mauve }}
$red       = {{ rgb red }}
$maroon    = {{ rgb maroon }}
$peach     = {{ rgb peach }}
$yellow    = {{ rgb yellow }}
$green     = {{ rgb green }}
$teal      = {{ rgb teal }}
$sky       = {{ rgb teal }}
$sapphire  = {{ rgb sapphire }}
$blue      = {{ rgb blue }}
$lavender  = {{ rgb lavender }}

$text      = {{ rgb text }}
$subtext1  = {{ rgb subtext1 }}
$subtext0  = {{ rgb subtext0 }}

$overlay2  = {{ rgb overlay2 }}
$overlay1  = {{ rgb overlay1 }}
$overlay0  = {{ rgb overlay0 }}

$surface2  = {{ rgb surface2 }}
$surface1  = {{ rgb surface1 }}
$surface0  = {{ rgb surface0 }}

$base      = {{ rgb base }}
$mantle    = {{ rgb mantle }}
$crust     = {{ rgb crust }}
